name: newsapp
description: "A news application"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.1.0
  dio: ^5.4.3+1
  google_fonts: ^6.2.1
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  provider: ^6.1.2
  characters: ^1.3.0
  internet_connection_checker: ^1.0.0+1
  flutter_slidable: ^3.1.0
  webview_flutter: ^4.8.0
  go_router: ^14.2.0
  cached_network_image: ^3.3.1
  share_plus: ^9.0.0
  intl_phone_field: ^3.2.0
  supabase_flutter: ^2.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  assets:
    - .env
    - assets/placeholder.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
